@startuml
class Vehicle {
  +drive()
}
class BaseVehicle
class OffRoadVehicle {
  +drive()
}
class SportsVehicle {
  +drive()
}

BaseVehicle --|> Vehicle

' OffRoadVehicle and SportsVehicle do NOT inherit from Vehicle in this example
@enduml
